---
title: "Mastering Distributions"
output: html_notebook
---

## Required Libraries
```{r}
library(poweRlaw)
library(ggplot2)
```

## R Markdown
```{r}
generate_power_law_data <- function(N, gamma, kmin = 1) {
  x <- seq(kmin, N)
  probs <- x^(-gamma)
  probs <- probs / sum(probs)
  sample(x, N, replace = TRUE, prob = probs)
}

N <- 10000
gamma_values <- c(2.2, 2.5, 3.0)
datasets <- lapply(gamma_values, function(gamma) generate_power_law_data(N, gamma))
names(datasets) <- paste0("gamma_", gamma_values)
```

## Including Plots
```{r}
fit_power_law <- function(data, kmin = 1) {
  m <- displ$new(data)
  m$setXmin(kmin)
  est <- estimate_pars(m)
  return(est)
}

fits <- lapply(datasets, fit_power_law)
fits
```


## Including Plots
```{r}
plot_data <- function(data, title) {
  m <- displ$new(data)
  est <- estimate_pars(m)
  m$setPars(est)
  plot(m, main = title)
  lines(m, col = "red")
}

par(mfrow = c(1, 3))
sapply(names(datasets), function(name) plot_data(datasets[[name]], name))
```

